# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

serialOceanTidesCorrections <- function(rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2) {
    .Call('_asteRisk_serialOceanTidesCorrections', PACKAGE = 'asteRisk', rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2)
}

parallelOceanTidesCorrections <- function(rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2) {
    .Call('_asteRisk_parallelOceanTidesCorrections', PACKAGE = 'asteRisk', rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2)
}

legendre <- function(n, m, angle) {
    .Call('_asteRisk_legendre', PACKAGE = 'asteRisk', n, m, angle)
}

gravityGradientSphericalCoords <- function(Pnm, dPnm, Cnm, Snm, lat, lon, d, R, GM, n, m) {
    .Call('_asteRisk_gravityGradientSphericalCoords', PACKAGE = 'asteRisk', Pnm, dPnm, Cnm, Snm, lat, lon, d, R, GM, n, m)
}

iauDtdb <- function(MJDTT) {
    .Call('_asteRisk_iauDtdb', PACKAGE = 'asteRisk', MJDTT)
}

