# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

angularSeparation <- function(x, y) {
    .Call('_asteRisk_angularSeparation', PACKAGE = 'asteRisk', x, y)
}

rotate3DVectorsAngleAxis <- function(x, axis, angle) {
    .Call('_asteRisk_rotate3DVectorsAngleAxis', PACKAGE = 'asteRisk', x, axis, angle)
}

rotate3DVectorAngleAxis <- function(x, axis, angle) {
    .Call('_asteRisk_rotate3DVectorAngleAxis', PACKAGE = 'asteRisk', x, axis, angle)
}

dvhat <- function(position, velocity) {
    .Call('_asteRisk_dvhat', PACKAGE = 'asteRisk', position, velocity)
}

vectorCrossProduct3D_cpp <- function(u, v) {
    .Call('_asteRisk_vectorCrossProduct3D_cpp', PACKAGE = 'asteRisk', u, v)
}

serialOceanTidesCorrections <- function(rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2) {
    .Call('_asteRisk_serialOceanTidesCorrections', PACKAGE = 'asteRisk', rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2)
}

parallelOceanTidesCorrections <- function(rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2) {
    .Call('_asteRisk_parallelOceanTidesCorrections', PACKAGE = 'asteRisk', rowTideNames, tideCnmSnmCoefficients, doodsonVars, Cnm, Snm, m1, m2)
}

legendre <- function(n, m, angle) {
    .Call('_asteRisk_legendre', PACKAGE = 'asteRisk', n, m, angle)
}

SPICE_i_dnnt_vec <- function(x) {
    .Call('_asteRisk_SPICE_i_dnnt_vec', PACKAGE = 'asteRisk', x)
}

SPICE_i_dnnt <- function(x) {
    .Call('_asteRisk_SPICE_i_dnnt', PACKAGE = 'asteRisk', x)
}

keplerVectorSolver <- function(evec1, evec2) {
    .Call('_asteRisk_keplerVectorSolver', PACKAGE = 'asteRisk', evec1, evec2)
}

gravityGradientSphericalCoords <- function(Pnm, dPnm, Cnm, Snm, lat, lon, d, R, GM, n, m) {
    .Call('_asteRisk_gravityGradientSphericalCoords', PACKAGE = 'asteRisk', Pnm, dPnm, Cnm, Snm, lat, lon, d, R, GM, n, m)
}

gravityGradientSphericalCoords_2 <- function(Pnm, dPnm, Cnm, Snm, lat, lon, d, R, GM, n, m) {
    .Call('_asteRisk_gravityGradientSphericalCoords_2', PACKAGE = 'asteRisk', Pnm, dPnm, Cnm, Snm, lat, lon, d, R, GM, n, m)
}

clenshawAllDerivatives_OLD <- function(t, N, Ta, Tb, Coeffs, derivativesOrder) {
    .Call('_asteRisk_clenshawAllDerivatives_OLD', PACKAGE = 'asteRisk', t, N, Ta, Tb, Coeffs, derivativesOrder)
}

clenshawAllDerivatives_NoIntegral <- function(t, N, XS1, XS2, Coeffs, derivativesOrder, xScaleUnitFactor) {
    .Call('_asteRisk_clenshawAllDerivatives_NoIntegral', PACKAGE = 'asteRisk', t, N, XS1, XS2, Coeffs, derivativesOrder, xScaleUnitFactor)
}

clenshawAllDerivatives <- function(t, N, XS1, XS2, Coeffs, derivativesOrder, xScaleUnitFactor, integral) {
    .Call('_asteRisk_clenshawAllDerivatives', PACKAGE = 'asteRisk', t, N, XS1, XS2, Coeffs, derivativesOrder, xScaleUnitFactor, integral)
}

iauDtdb <- function(MJDTT) {
    .Call('_asteRisk_iauDtdb', PACKAGE = 'asteRisk', MJDTT)
}

